<footer>
    <div class="contenido-footer">

        <!-- Primera columna-->
        <div class="columna-footer columna-logo">
            <img src="<?= $rutaBase ?>img/gtiBlanco.svg" alt="logo">
            <p class="elementos-footer">Liderando la innovación en tecnología educativa</p>
        </div>

        <!-- Segunda columna-->
        <div class="columna-footer">
            <h4>Enlaces rápidos</h4>
            <ul>
                <li><a class="elementos-footer" href="<?= $rutaBase ?>catalogo.php">Catálogo</a></li>
                <li><a class="elementos-footer" href="<?= $rutaBase ?>preguntasFrecuentes.php">Preguntas Frecuentes</a></li>
                <li><a class="elementos-footer" href="<?= $rutaBase ?>contacto.php">Contacto</a></li>
            </ul>
        </div>

        <!-- Tercera columna-->
        <div class="columna-footer">
            <h4>Contacto</h4>
            <ul>
                <li class="elementos-footer">Email: info@gti.edu</li>
                <li class="elementos-footer">Tel: +34 900 123 456</li>
            </ul>
        </div>
    </div>
</footer>
